### ISSUE TITLE
包裹详情

### ISSUE THREAD

**Issue by JimmyLv** [JimmyLv/reading#721]
## &#21253;&#35065;&#35814;&#24773;<br><br><br>
September 8, 2017 at 12:33PM<br>
via Instapaper https://starwell.sudiyi.cn/dist/module/bod.html?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmcm9tIjoic21zIiwic2R5X29yZGVyX2lkIjoiOTE1MDQ3NzQ5MDU2MDAxMDc0ODAyMDY3IiwibGF0dGljZV9pZCI6NzM1NjAsIm1vYmlsZSI6IjE4NTAyODMwODAzIn0.0bm8_pzBkJmnu_D4XsM2-PZXOg5wQRduFKG74JJX5sM

**Comment by linesh-simplicity** [comment]
啧……仄你都扔下来233

**Comment by JimmyLv** [comment]
ahaha, it's a bug!!!

**Comment by linesh-simplicity** [comment]
包裹已经帮你领了。
