### ISSUE TITLE
Gitflow有害论  ThoughtWorks洞见

### ISSUE THREAD

**Issue by JimmyLv** [JimmyLv/reading#804]
## Gitflow&#26377;&#23475;&#35770; &ndash; ThoughtWorks&#27934;&#35265;<br>
We firmly believe that long-lived version-control branches harm valuable engineering practices such as continuous integration, and this belief underlies our&hellip;<br><br>
September 22, 2017 at 06:51PM<br>
via Instapaper http://insights.thoughtworks.cn/gitflow-consider-harmful/

**Comment by linesh-simplicity** [comment]
@TL
