### ISSUE TITLE
WebStorm 2017.3 EAP 173.3302 coverage reports for Jest

### ISSUE THREAD

**Issue by JimmyLv** [JimmyLv/reading#945]
## WebStorm 2017.3 EAP, 173.3302 coverage reports for Jest<br>
This week&rsquo;s WebStorm 2017.3 EAP build (173.3302.13) is now available! You can update via Toolbox App , or download the build here and install it side by side&hellip;<br><br>
October 22, 2017 at 10:09AM<br>
via Instapaper https://blog.jetbrains.com/webstorm/2017/10/webstorm-2017-3-eap-173-3302/

**Comment by linesh-simplicity** [comment]
Awesome.
